# -*- coding: utf-8 -*-
import sys
import time

# Form implementation generated from reading ui file 'game.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QMutex


class Ui_gameWindow(object):
    def __init__(self, Client):
        self.client = Client
        self.game_starting = None
        self.opened = False

    def setupUi(self, gameWindow):
        print("entered setup")
        gameWindow.setObjectName("gameWindow")
        gameWindow.resize(548, 600)
        self.centralwidget = QtWidgets.QWidget(gameWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.game_table = QtWidgets.QTableWidget(self.centralwidget)
        self.game_table.setGeometry(QtCore.QRect(0, 0, 801, 581))
        self.game_table.setStyleSheet(";background-color:rgb(255, 255, 255);\n"
                                      "border:1px solid red\n"
                                      ";gridline-color: rgb(170, 85, 255);\n"
                                      "text-color:rgb(255, 85, 127)")
        self.game_table.setAlternatingRowColors(True)
        self.game_table.setObjectName("game_table")
        self.game_table.setColumnCount(5)
        self.game_table.setRowCount(3)
        self._mutex = QMutex()
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.game_table.setHorizontalHeaderItem(4, item)
        for i in range(3):
            for j in range(5):
                item = QtWidgets.QTableWidgetItem()
                self.game_table.setItem(i, j, item)
        self.game_table.horizontalHeader().setStretchLastSection(False)
        self.game_table.verticalHeader().setCascadingSectionResizes(False)
        self.game_table.verticalHeader().setStretchLastSection(False)
        self.round_time = QtWidgets.QLabel(self.centralwidget)
        self.round_time.setGeometry(QtCore.QRect(10, 350, 461, 81))
        self.round_time.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.round_time.setObjectName("round_time")
        self.round_time.hide()
        self.word_text = QtWidgets.QLineEdit(self.centralwidget)
        self.word_text.setGeometry(QtCore.QRect(50, 220, 251, 61))
        self.word_text.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.word_text.setObjectName("word_text")
        self.word_text.hide()
        self.enter_word_label = QtWidgets.QLabel(self.centralwidget)
        self.enter_word_label.setGeometry(QtCore.QRect(50, 180, 251, 31))
        self.enter_word_label.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.enter_word_label.setObjectName("enter_word_label")
        self.enter_word_label.hide()
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(300, 220, 191, 61))
        self.submit_button.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.submit_button.setObjectName("submit_button")
        self.submit_button.hide()
        self.return_button = QtWidgets.QPushButton(self.centralwidget)
        self.return_button.setGeometry(QtCore.QRect(10, 300, 281, 61))
        self.return_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                         "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.return_button.setObjectName("return_button")
        self.return_button.hide()
        self.play_again_button = QtWidgets.QPushButton(self.centralwidget)
        self.play_again_button.setGeometry(QtCore.QRect(290, 300, 211, 61))
        self.play_again_button.setStyleSheet(";background-color: rgb(162, 47, 255);\n"
                                             "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.play_again_button.setObjectName("play_again_button")
        self.play_again_button.hide()
        self.won_label = QtWidgets.QLabel(self.centralwidget)
        self.won_label.setGeometry(QtCore.QRect(350, 120, 271, 51))
        self.won_label.setStyleSheet("\n"
                                     "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.won_label.setObjectName("won_label")
        self.won_label.hide()
        self.lost_label = QtWidgets.QLabel(self.centralwidget)
        self.lost_label.setGeometry(QtCore.QRect(60, 120, 271, 41))
        self.lost_label.setStyleSheet("\n"
                                      "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.lost_label.setObjectName("lost_label")
        self.lost_label.hide()
        self.tied_label = QtWidgets.QLabel(self.centralwidget)
        self.tied_label.setGeometry(QtCore.QRect(140, 480, 271, 41))
        self.tied_label.setStyleSheet("\n"
                                      "font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.tied_label.setObjectName("tied_label")
        self.tied_label.hide()
        self.waiting_text = QtWidgets.QLabel(self.centralwidget)
        self.waiting_text.setGeometry(QtCore.QRect(10, 420, 371, 41))
        self.waiting_text.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.waiting_text.setObjectName("waiting_text")
        self.one = QtWidgets.QLabel(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(380, 420, 16, 41))
        self.one.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.one.setObjectName("one")
        self.one.hide()
        self.two = QtWidgets.QLabel(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(400, 420, 20, 41))
        self.two.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.two.setObjectName("two")
        self.two.hide()
        self.three = QtWidgets.QLabel(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(420, 420, 16, 41))
        self.three.setStyleSheet("font: 75 8pt \"Magneto\"; font-size: 35px;height: 20px;width: 45px;")
        self.three.setObjectName("three")
        self.three.hide()
        gameWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(gameWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 548, 21))
        self.menubar.setObjectName("menubar")
        gameWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(gameWindow)
        self.statusbar.setObjectName("statusbar")
        gameWindow.setStatusBar(self.statusbar)

        self.retranslateUi(gameWindow)
        QtCore.QMetaObject.connectSlotsByName(gameWindow)
        if self.client.voice is False:
            self.submit_button.show()
            self.word_text.show()
            self.enter_word_label.show()
        self.check_for_button(gameWindow)

    def retranslateUi(self, gameWindow):
        _translate = QtCore.QCoreApplication.translate
        gameWindow.setWindowTitle(_translate("gameWindow", "MainWindow"))
        item = self.game_table.verticalHeaderItem(0)
        item.setText(_translate("gameWindow", "letter1"))
        item = self.game_table.verticalHeaderItem(1)
        item.setText(_translate("gameWindow", "letter2"))
        item = self.game_table.verticalHeaderItem(2)
        item.setText(_translate("gameWindow", "letter3"))
        item = self.game_table.horizontalHeaderItem(0)
        item.setText(_translate("gameWindow", "country"))
        item = self.game_table.horizontalHeaderItem(1)
        item.setText(_translate("gameWindow", "city"))
        item = self.game_table.horizontalHeaderItem(2)
        item.setText(_translate("gameWindow", "boy name"))
        item = self.game_table.horizontalHeaderItem(3)
        item.setText(_translate("gameWindow", "animal"))
        item = self.game_table.horizontalHeaderItem(4)
        item.setText(_translate("gameWindow", "points"))
        __sortingEnabled = self.game_table.isSortingEnabled()
        self.game_table.setSortingEnabled(False)
        self.game_table.setSortingEnabled(__sortingEnabled)
        self.round_time.setText(_translate("gameWindow", "round timer 15 seconds"))
        self.enter_word_label.setText(_translate("gameWindow", "enter word"))
        self.submit_button.setText(_translate("gameWindow", "submit"))
        self.return_button.setText(_translate("gameWindow", "return to lobby"))
        self.play_again_button.setText(_translate("gameWindow", "play again"))
        self.won_label.setText(_translate("gameWindow", "you won!!"))
        self.lost_label.setText(_translate("gameWindow", "you lost..."))
        self.tied_label.setText(_translate("gameWindow", "you tied..."))
        self.waiting_text.setText(_translate("gameWindow", "waiting for players"))
        self.one.setText(_translate("gameWindow", "."))
        self.two.setText(_translate("gameWindow", "."))
        self.three.setText(_translate("gameWindow", "."))

    def check_for_button(self, MainWindow):
        self.return_button.clicked.connect(lambda: self.return_pressed(MainWindow))
        print("print1")
        self.submit_button.clicked.connect(self.send_word)
        print("print2")
        self.play_again_button.clicked.connect(self.play_again_pressed)

    def play_again_pressed(self):
        print("continuepressed")
        self.client.screen_state = 2

    def send_word(self):
        print("sendpressed")
        self._mutex.lock()
        self.client.curr_word = self.word_text.text()
        self._mutex.unlock()

    def return_pressed(self, MainWindow):
        print("continuepressed")
        self.client.screen_state = 2
        MainWindow.close()

    def insert_value(self, category, round_num, word):
        _translate = QtCore.QCoreApplication.translate
        item = self.game_table.item(round_num - 1, category)
        item.setText(_translate("gameWindow", word))

    def start_round(self):
        if self.client.voice is False:
            self.enter_word_label.show()
            self.submit_button.show()
            self.word_text.show()
        self.game_starting.show()
        time.sleep(1)
        self.one.show()
        time.sleep(1)
        self.two.show()
        time.sleep(1)
        self.three.show()
        time.sleep(1)
        self.game_starting.hide()
        self.one.hide()
        self.two.hide()
        self.three.hide()

    def set_letter(self, round_num, letter):
        _translate = QtCore.QCoreApplication.translate
        item = self.game_table.verticalHeaderItem(round_num - 1)
        item.setText(_translate("gameWindow", letter))

    def waiting_for_players(self):
        while self.client.game_start is False:
            self.one.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.two.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.three.show()
            time.sleep(1)
            if self.client.game_start is True:
                break
            self.one.hide()
            self.two.hide()
            self.three.hide()
            time.sleep(1)
        self.round_time.show()
        self.one.hide()
        self.two.hide()
        self.three.hide()
        self.waiting_text.hide()


def show_game(window):
    app2 = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    window.setupUi(MainWindow)
    MainWindow.show()
    window.opened = True
    sys.exit(app2.exec_())
